name: PI-Test-1
on:
  workflow_dispatch:

concurrency:
  group: my-workflow-group

jobs:
  Calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run script
        run: node script.js
